### ISSUE TITLE
Usage without Middleware

### ISSUE THREAD

**Issue by Tigla** [toni-suarez/laravel-utm-parameter#9]
Thank you for the project!
I would like to suggest improvements:
1. There is a need to use the package when the shouldAcceptUtmParameter() condition is not true. For example POST requests. Then in this case an empty array will always be received (because the boot() method will not be run), and I would like to retrieve the session without writing to it.
2. It would also be nice to extend the conditions shouldAcceptUtmParameter() to add an exception router configuration.

**Comment by toni-suarez** [comment]
For now you could extend the middleware by creating your own and overwrite `shouldAcceptUtmParameter()` method. This will allow you to customize the conditions under which UTM parameters are accepted, including handling POST requests and adding an exception router configuration.

**Example**:

```bash
php artisan make:middleware CustomMiddleware
```

```php
<?php

use Illuminate\Http\Request;
use Suarez\UtmParameter\Middleware\UtmParameters;

class CustomMiddleware extends UtmParameters
{
    /**
     * Determines whether the given request/response pair should accept UTM-Parameters.
     *
     * @param \Illuminate\Http\Request  $request
     *
     * @return bool
     */
    protected function shouldAcceptUtmParameter(Request $request)
    {
        return $request->isMethod('GET') || $request->isMethod('POST');
    }
}


```

And finally update your Kernel.php or bootstrap/app.php to use the CustomMiddleware:
```php
$middleware->web([CustomMiddleware::class]);
```

**Comment by Tigla** [comment]
The proposed solution is clear, but my point is another... 
To make a static method (or even apply this constructor), which would get the current session state from utm and use it everywhere, both inside Middleware and outside.
That it would be possible to work with the package without calling Middleware where it is not needed.
For example, there is a router where Middleware is not needed (no need to save utm), but we need to get data about previously collected utm.

**Comment by toni-suarez** [comment]
Thank you for your suggestion. 
Now it's possible to use it also without middleware. Take a look: [Use as Facade](https://github.com/toni-suarez/laravel-utm-parameter?tab=readme-ov-file#use-as-facade) 

Remove the middleware and add that facade where you need to.

```php
use Suarez\UtmParameter\Facades\UtmParameter;

class IndexController {
  public function index(Request $request)
  {
      UtmParameter::boot($request);
  }
}

class SomeDifferentController {
  public function index(Request $request)
  {
      $source = UtmParameter::get('source');
  }
}
```

**Comment by Tigla** [comment]
If you call `UtmParameter::get('source') `- it will always return an empty value. There is no need to execute `UtmParameter::boot($request)`, because there is no request or there is no need to write utm data to the session, but only to retrieve it.

I suggest that when calling `UtmParameter::all()` to get data from the session directly that would not be dependent on Request, and in Middleware to do only saving to the session.

**Comment by toni-suarez** [comment]
In case you don't want to use the middleware, which updates everything within the session via `UtmParameter::boot($request);` with every GET-Request, you can use the facade technique.

In this case you need to call `UtmParameter::boot($request);` once, to retrieve the UTM-Parameters. It's stored inside the session and you can easily use `UtmParameter::all()`, `UtmParameter::get()`, `UtmParameter::has()` or `UtmParameter::contains()`.


```php
Route::get('/', function (Request $request) {
    // initial call to get the UTM Parameters from the Request-Object
    UtmParameter::boot($request);

    return view('index');
});

Route::get('/detail', function (Request $request) {
     // Retrieve parameter from the session
    $source = UtmParameter::get('source');
    dd($source);
    return view('detail');
});
```

You could also work with middleware-aliases and apply it only on routes you want to check for these parameters.

**Comment by Tigla** [comment]
Thank you.
